[package]
name = "libtxc"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
crate-type = ["lib"]
doctest = false

[[bin]]
name = "example"
path = "src/example.rs"

[dependencies]
winapi  = {version = "0.3.8", features = ["errhandlingapi", "libloaderapi"]}

[profile.release]
lto = "thin"
